df<-read.csv("POI_n104_raw.csv",stringsAsFactors=FALSE,check.names=FALSE)
names(df)<-gsub("\n"," ",names(df))
df<-df[!is.na(df$`first author (year)`),]
df$NMVr_1L<-ifelse(tolower(df$`1st line standard or prolonged NMV-r treatment  [yes / no] ?`)=="yes",1,0)
df$OtherAV_1L<-ifelse(tolower(df$`1st line treatment any other antiviral drugs  (days) and [dosage]`)!="none"|tolower(df$`2nd line any other concomitant antiviral therapy (days) / [dosages]`)!="none",1,0)
df$path<-paste0(ifelse(df$NMVr_1L==1,"Yes","No"),"/",ifelse(df$OtherAV_1L==1,"Yes","No"))
df$path<-factor(df$path,levels=c("Yes/Yes","Yes/No","No/Yes","No/No"))
tab<-as.data.frame(table(df$path))
stopifnot(sum(tab$Freq)==104)
tab$pct<-round(tab$Freq/104*100)
tab$axis1<-rep(c("NMV-r 1st Line: Yes","NMV-r 1st Line: No"),2)
tab$axis2<-rep(c("Other AV 1st Line: Yes","Other AV 1st Line: No"),each=2)
tab$fill<-tab$Var1
tab$label<-paste0("n = ",tab$Freq," (",tab$pct,"%)")
library(ggsankeyfier)
sank<-pivot_stages_longer(tab,stages_from=c("axis1","axis2"),values_from="Freq",additional_aes_from=c("fill","label"))
library(ggplot2)
pos<-position_sankey()
p<-ggplot(sank,aes(x=stage,y=Freq,group=node,connector=connector,edge_id=edge_id))+geom_sankeyedge(aes(fill=fill),position=pos,alpha=.8,show.legend=FALSE)+geom_sankeynode(position=pos,show.legend=FALSE)+geom_text(aes(label=label),position=pos,stat="sankeyedge",size=3,color="black")+scale_fill_manual(values=c("#E69F00","#56B4E9","#009E73","#999999"))+theme_minimal()+theme(axis.text=element_blank(),axis.title=element_blank(),panel.grid=element_blank())
print(p)
# ggsave("figure_POI_Sankey_test.png",p,dpi=300,width=16,units="cm")
# ggsave("figure_POI_Sankey_test.pdf",p,dpi=300,width=16,units="cm")
